remote_theme: 256-Foundation/midnight-theme
title: Assembling Freedom
description: A weekly Bitcoin mining newsletter
github:
  repository_url: https://256foundation.substack.com/
  owner_url: https://256foundation.org
